export const hotelType = [
  "Resort",
  "Boutique Hotel",
  "Motel",
  "Bed and Breakfast",
  "Apartment Hotel",
  "Luxury Hotel",
  "Budget Hotel",
  "Villa",
  "Cottage",
  "Guest House",
  "Eco Hotel",
  "Business Hotel",
  "Airport Hotel",
  "Family",
  "Romantic",
];

export const hotelFacilties = [
  "Free Wi-Fi",
  "Swimming Pool",
  "Fitness Center",
  "Spa",
  "Restaurant",
  "Bar",
  "24-Hour Front Desk",
  "Room Service",
  "Parking",
  "Air Conditioning",
  "Conference Rooms",
  "Laundry Service",
  "Airport Shuttle",
];
